name: JavaHL Build

on:
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: |
          mvn --batch-mode package
          ARTIFACT_PATHNAME=$(ls ./target/*.jar | head -n 1)
          ARTIFACT_NAME=$(basename $ARTIFACT_PATHNAME .jar)
          echo ARTIFACT_PATHNAME=$ARTIFACT_PATHNAME >> $GITHUB_ENV
          echo ARTIFACT_NAME=$ARTIFACT_NAME >> $GITHUB_ENV

      - name: Archive Build Output
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATHNAME }}

      - name: Publish package
        if: github.event_name == 'release'
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
